### ISSUE TITLE
Wifi connexion in app

### ISSUE THREAD

**Issue by ismael94370** [myvobot/dock-mini-apps#1]
Hello, I try to create an application who's call an api. My Vobot say I'm successfully connected to the wifi but when I built the application and check the connexion with the request : print(net.connected()) he return me "True" (Not connected).

How can I connect my app to the Wifi ?

**Comment by pumpkin-zbh** [comment]
Apologies for the delayed response.

Based on the return value of your function, it appears that your device is correctly connected to the network. The net.connected() function returning True indicates that the device is connected to Wi-Fi. We apologize for the misleading documentation and will update it promptly to reflect the correct information.

If you have any further questions or encounter any other issues, please feel free to reach out.

**Comment by ismael94370** [comment]
Ok thank you for your answer. My app work now.
